services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: Eclipseworks.TaskManagement
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Will00"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: